r"""Author RemoveKeepRule(Index: int) -> void on Menu_ModController -- simplified per user's
correction: the caller (the rules-list UI) already knows the KeepRulesV2 index for whichever row
was clicked, so there's no need to re-derive it via a Station/TemplateID search loop (the first,
overcomplicated version of this function). This version is just a bounds check + removal.

Body-only fragment (K2Node_FunctionEntry can't be pasted) -- 2 hand-wires needed from the real
FunctionEntry after paste:
  Entry.then  -> knot_exec.InputPin
  Entry.Index -> knot_index.InputPin

Structure:
  IsValidIndex(KeepRulesV2, Index) -> IfThenElse:
    valid (then): Array_RemoveIndex(KeepRulesV2, Index) -> print "rule removed"
    invalid (else): print "invalid index, nothing removed"

Array_RemoveIndex: same clone-from-Array_Add technique as the first version (no captured
precedent in this project, flagged for proofread same as before).
Array_IsValidIndex: cloned from the real Array_Contains template (library/actor/
array_contains_int.t3d) -- same wildcard-array-plus-one-int-param-returning-bool pure-function
shape, retargeted. Also no captured precedent -- flagged for proofread.
"""
import sys

import os, pathlib
CCMOD = os.environ.get("CCMOD_HOME") or str(pathlib.Path(__file__).resolve().parents[3] / "claude-conan-modder")
sys.path.insert(0, CCMOD)
from ccmod.t3d import parse, connect, connect_exec, auto_layout
from ccmod.t3d.generator import instantiate
from ccmod.t3d.model import Graph

import pathlib
MOD = str(pathlib.Path(__file__).resolve().parents[2])
LIB = CCMOD + r"\library"
WLIB = MOD + r"\.ccmod\library"
UPSERT_SRC = MOD + r"\.ccmod\graphs\menu_addkeeprule_upsert_full.t3d"

KEEPRULE_STRUCT = '''"/Script/CoreUObject.UserDefinedStruct'/Game/Mods/Menu/S_KeepRule.S_KeepRule'"'''
MENU_MC_BGC = '''"/Script/Engine.BlueprintGeneratedClass'/Game/Mods/Menu/Menu_ModController.Menu_ModController_C'"'''


def pin(n, name, output=None):
    p = n.pin_by_name(name, output=output)
    assert p, f"{n.name} has no pin {name}"
    return p


def setf(n, pn, k, raw, output=None):
    pin(n, pn, output=output)._set(k, raw)


def tmpl_file(path):
    t = parse(open(path, encoding="utf-8-sig").read())
    for n in t.nodes:
        for p in n.pins:
            p.links = []
    return t


import copy


def find_by_raw(src_graph, needle, want_class=None):
    for n in src_graph.nodes:
        if want_class and not n.class_path.endswith(want_class):
            continue
        raw = " ".join(t for k, t in n.body if k == "raw")
        if needle in raw:
            nn = copy.deepcopy(n)
            for p in nn.pins:
                p.links = []
            return Graph(nodes=[nn])
    raise KeyError(needle)


IFTHENELSE_RAW = '''Begin Object Class=/Script/BlueprintGraph.K2Node_IfThenElse Name="K2Node_IfThenElse_0"
   NodeGuid=00000000000000000000000000000000
   CustomProperties Pin (PinId=00000000000000000000000000000001,PinName="execute",PinType.PinCategory="exec",PinType.PinSubCategory="",PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False)
   CustomProperties Pin (PinId=00000000000000000000000000000002,PinName="Condition",PinType.PinCategory="bool",PinType.PinSubCategory="",PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,DefaultValue="true",AutogeneratedDefaultValue="true",PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False)
   CustomProperties Pin (PinId=00000000000000000000000000000003,PinName="then",PinFriendlyName=NSLOCTEXT("K2Node", "true", "true"),Direction="EGPD_Output",PinType.PinCategory="exec",PinType.PinSubCategory="",PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False)
   CustomProperties Pin (PinId=00000000000000000000000000000004,PinName="else",PinFriendlyName=NSLOCTEXT("K2Node", "false", "false"),Direction="EGPD_Output",PinType.PinCategory="exec",PinType.PinSubCategory="",PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False)
End Object'''
IFTHENELSE_T = parse(IFTHENELSE_RAW)

upsert_src = parse(open(UPSERT_SRC, encoding="utf-8-sig").read())

KNOT_T = tmpl_file(LIB + r"\flow\knot.t3d")
ADD_T = tmpl_file(LIB + r"\array\array_add.t3d")
CONTAINS_T = tmpl_file(LIB + r"\actor\array_contains_int.t3d")
GET_KEEPRULESV2_T = tmpl_file(WLIB + r"\stocker\get_keeprules_v2.t3d")
PRINT_T = find_by_raw(upsert_src, 'MemberName="PrintString"', want_class="K2Node_CallFunction")


def make_print(text):
    n = add(PRINT_T)
    setf(n, "InString", "DefaultValue", f'"{text}"')
    return n


def type_knot(n, category, subcat_obj="None", container="None"):
    for pn in ("InputPin", "OutputPin"):
        setf(n, pn, "PinType.PinCategory", f'"{category}"')
        setf(n, pn, "PinType.PinSubCategoryObject", subcat_obj)
        setf(n, pn, "PinType.ContainerType", container)


g = Graph()


def add(t):
    return instantiate(t, g)[0]


# ---- entry hand-wires (2: exec, Index) ----------------------------------------------------------
knot_exec = add(KNOT_T)
type_knot(knot_exec, "exec")
knot_index = add(KNOT_T)
type_knot(knot_index, "int")

# ---- Array_IsValidIndex: cloned from the real Array_Contains template ----------------------------
isvalid_call = add(CONTAINS_T)
isvalid_call._replace_prop(
    "FunctionReference",
    '(MemberParent="/Script/CoreUObject.Class\'/Script/Engine.KismetArrayLibrary\'",MemberName="Array_IsValidIndex")',
)
setf(isvalid_call, "TargetArray", "PinType.PinCategory", '"struct"')
setf(isvalid_call, "TargetArray", "PinType.PinSubCategoryObject", KEEPRULE_STRUCT)
setf(isvalid_call, "TargetArray", "PinType.ContainerType", "Array")
itemtofind_pin = pin(isvalid_call, "ItemToFind")
itemtofind_pin._set("PinName", '"Index"')

# ---- Array_RemoveIndex: cloned from the real Array_Add template ----------------------------------
removeindex_call = add(ADD_T)
removeindex_call._replace_prop(
    "FunctionReference",
    '(MemberParent="/Script/CoreUObject.Class\'/Script/Engine.KismetArrayLibrary\'",MemberName="Array_RemoveIndex")',
)
setf(removeindex_call, "TargetArray", "PinType.PinCategory", '"struct"')
setf(removeindex_call, "TargetArray", "PinType.PinSubCategoryObject", KEEPRULE_STRUCT)
setf(removeindex_call, "TargetArray", "PinType.ContainerType", "Array")
newitem_pin = pin(removeindex_call, "NewItem")
newitem_pin._set("PinName", '"IndexToRemove"')
newitem_pin._set("PinType.PinCategory", '"int"')
newitem_pin._set("PinType.PinSubCategoryObject", "None")
newitem_pin._set("PinType.bIsReference", "False")
newitem_pin._set("PinType.bIsConst", "False")
returnvalue_pin = pin(removeindex_call, "ReturnValue", output=True)
removeindex_call.body = [(k, it) for (k, it) in removeindex_call.body if not (k == "pin" and it is returnvalue_pin)]

# ---- KeepRulesV2 gets (one per consumer -- pure fan-out is free) --------------------------------
keeprules_get1 = add(GET_KEEPRULESV2_T)
setf(keeprules_get1, "self", "PinType.PinSubCategoryObject", MENU_MC_BGC, output=False)
keeprules_get2 = add(GET_KEEPRULESV2_T)
setf(keeprules_get2, "self", "PinType.PinSubCategoryObject", MENU_MC_BGC, output=False)

ite_valid = add(IFTHENELSE_T)
print_removed = make_print("MENU_RULESLIST: rule removed")
print_invalid = make_print("MENU_RULESLIST: invalid index, nothing removed")

# =====================  WIRING  ==================================================================
connect(keeprules_get1, "KeepRulesV2", isvalid_call, "TargetArray")
connect(knot_index, "InputPin", isvalid_call, "Index")

connect_exec(knot_exec, ite_valid, "OutputPin", "execute")
connect(isvalid_call, "ReturnValue", ite_valid, "Condition")

connect_exec(ite_valid, removeindex_call, "then", "execute")
connect(keeprules_get2, "KeepRulesV2", removeindex_call, "TargetArray")
connect(knot_index, "InputPin", removeindex_call, "IndexToRemove")
connect_exec(removeindex_call, print_removed, "then", "execute")

connect_exec(ite_valid, print_invalid, "else", "execute")

auto_layout(g.nodes, origin=(0, 0), dx=280, dy=220, per_column=6)

# --- validate --------------------------------------------------------------------------------
problems = []
names = {n.name for n in g.nodes}
for n in g.nodes:
    for p in n.pins:
        for (lnn, lp) in p.links:
            if lnn not in names:
                problems.append(f"{n.name}.{p.name} -> missing {lnn}")
                continue
            other = g.by_name(lnn).pin_by_id(lp)
            if other is None:
                problems.append(f"{n.name}.{p.name} -> {lnn} missing pin {lp}")
                continue
            if (n.name, p.pin_id) not in other.links:
                problems.append(f"non-reciprocal: {n.name}.{p.name} -> {lnn}.{other.name}")

wilds = [(n.name, p.name) for n in g.nodes for p in n.pins
         if p._get("PinType.PinCategory") == '"wildcard"']
assert not wilds, f"unresolved wildcards: {wilds}"

out = MOD + r"\.ccmod\graphs\menu_removekeeprule_v2_body.t3d"
open(out, "w", encoding="utf-8").write(g.render())
print(f"nodes: {len(g.nodes)}   wrote: {out}")
print(f"problems: {len(problems)}")
for pr in problems:
    print("  !", pr)
print()
print("hand-wires needed after paste (from the REAL FunctionEntry):")
print(f"  Entry.then  -> {knot_exec.name}.InputPin")
print(f"  Entry.Index -> {knot_index.name}.InputPin")
