"""Complete the debug harness in place, starting from the REAL post-paste graph
(session 16: user hand-added GatherNearbyBenches + both AddKeepRule calls, but
forgot GatherNearbyStorageContainers and RunSweep, and wired rule2.then straight
to PrintString). This script works on the actual live graph (pulled via
`ccmod pull`), not a from-scratch template, so every existing NodeGuid/PinId/
FunctionReference (including the real MemberGuids UE assigned when the user
added GatherNearbyBenches/AddKeepRule by hand) is preserved untouched.

Fixes applied:
1. GatherNearbyBenches's Range pin was left at its autogenerated "0.0" default
   (never actually set to 3000) -- would return an empty array every time.
   Fixed to 3000.0. GatherNearbyStorageContainers gets the same value.
2. Delay bumped from 8s to 90s per the user's ask: more time to walk over and
   place test items in the bench/chest before the harness fires.
3. GatherNearbyStorageContainers and RunSweep added as same-class self-calls,
   built by CLONING the real, already-proven-to-paste GatherNearbyBenches/
   AddKeepRule nodes (structurally identical signature for the former; the
   exec/self shape trimmed down for the latter's void/no-args signature) and
   swapping FunctionReference's MemberName -- NOT the from-scratch synthetic
   K2Node_CallFunction template that silently failed to paste in session 15.
   MemberGuid is deliberately omitted (bSelfContext=True, name-only) since we
   have no real captured GUID for these two specific functions; this is the
   one part of this rebuild without a proven precedent -- verify after paste
   that both new nodes show their real parameter pins, not a broken/orphan
   node, before compiling.
4. Rewires rule2.then -> GatherNearbyStorageContainers.execute -> RunSweep.execute
   -> PrintString.execute (was rule2.then -> PrintString.execute directly).
"""
import sys

CCMOD = r"<CCMOD_HOME>"
sys.path.insert(0, CCMOD)
from ccmod.t3d import parse, connect, connect_exec
from ccmod.t3d.generator import instantiate
from ccmod.t3d.model import Graph

MOD = r"<MOD_ROOT>"
SRC = MOD + r"\.ccmod\graphs\menu_debug_harness_postpaste.t3d"

g = parse(open(SRC, encoding="utf-8-sig").read())


def by_name(name):
    n = g.by_name(name)
    assert n, f"missing node {name}"
    return n


def by_func(member_name):
    for n in g.nodes:
        for k, t in n.body:
            if k == "raw" and t.lstrip().startswith("FunctionReference=") and f'MemberName="{member_name}"' in t:
                return n
    raise KeyError(member_name)


def setf(n, pn, k, raw, output=None):
    n.pin_by_name(pn, output=output)._set(k, raw)


delay = by_func("Delay")
setf(delay, "Duration", "DefaultValue", '"90.000000"')

bench_call = by_func("GatherNearbyBenches")
setf(bench_call, "Range", "DefaultValue", '"3000.0"')

rule_nodes = [n for n in g.nodes if any(k == "raw" and t.lstrip().startswith("FunctionReference=") and 'MemberName="AddKeepRule"' in t for k, t in n.body)]
assert len(rule_nodes) == 2
printstring = by_func("PrintString")
rule2 = next(n for n in rule_nodes if any(
    p.name == "then" and p.is_output and (printstring.name, printstring.pin_by_name("execute", output=False).pin_id) in p.links
    for p in n.pins
))

knot_desk = by_name("K2Node_Knot_623")


def clone_stripped(node, drop_pins=()):
    import copy
    nn = copy.deepcopy(node)
    nn.body = [
        (k, item) for (k, item) in nn.body
        if not (k == "pin" and item.name in drop_pins)
    ]
    for p in nn.pins:
        p.links = []
    return Graph(nodes=[nn])

# GatherNearbyStorageContainers: identical signature to GatherNearbyBenches
# (AnchorActor: Actor, Range: float) -> Array<Actor>; clone wholesale.
gnsc_tmpl = clone_stripped(bench_call)
gnsc = instantiate(gnsc_tmpl, g)[0]
gnsc._replace_prop("FunctionReference", '(MemberName="GatherNearbyStorageContainers",bSelfContext=True)')
gnsc.set_position(2400, 640)

# RunSweep: void, no params -- clone AddKeepRule's shape and drop its 4 data pins.
runsweep_tmpl = clone_stripped(rule2, drop_pins=("Station", "TemplateID", "Keep", "KeepAll"))
runsweep = instantiate(runsweep_tmpl, g)[0]
runsweep._replace_prop("FunctionReference", '(MemberName="RunSweep",bSelfContext=True)')
runsweep.set_position(2720, 640)

# --- rewire ---------------------------------------------------------------
rule2_then = rule2.pin_by_name("then", output=True)
printstring_exec = printstring.pin_by_name("execute", output=False)
rule2_then.links = []
printstring_exec.links = []

connect_exec(rule2, gnsc)
connect(knot_desk, "OutputPin", gnsc, "AnchorActor")
setf(gnsc, "Range", "DefaultValue", '"3000.0"')
connect_exec(gnsc, runsweep)
connect_exec(runsweep, printstring)

problems = []
names = {n.name for n in g.nodes}
for n in g.nodes:
    for p in n.pins:
        for (lnn, lp) in p.links:
            if lnn not in names:
                problems.append(f"{n.name}.{p.name} -> missing {lnn}")
                continue
            other = g.by_name(lnn).pin_by_id(lp)
            if other is None:
                problems.append(f"{n.name}.{p.name} -> {lnn} missing pin {lp}")
                continue
            if (n.name, p.pin_id) not in other.links:
                problems.append(f"non-reciprocal: {n.name}.{p.name} -> {lnn}.{other.name}")

out = MOD + r"\.ccmod\graphs\menu_debug_harness_v2_full.t3d"
open(out, "w", encoding="utf-8").write(g.render())
print(f"Full harness v2: nodes={len(g.nodes)} wrote={out} problems={len(problems)}")
for pr in problems:
    print("  !", pr)
print(f"  new nodes: {gnsc.name} (GatherNearbyStorageContainers), {runsweep.name} (RunSweep)")
print(f"  Delay Duration -> 90.0, GatherNearbyBenches Range -> 3000.0, new node Range -> 3000.0")
