"""Author TidyManagedStations() on Menu_ModController -- the verified pass-1 tidy port
(session 15 full BFS trace, see stocker-menu-pivot memory). Void function, no params, no return --
only ONE hand-wire needed (Entry.then -> the start of this body), no output knots at all.

Structure (fully traced, not guessed):
  ForEachLoop(ManagedStations) as Station
    Array_Clear(RuleTemplateID)
    ForEachLoop(KeepRulesV2) as Rule
      Break Rule -> Container/TemplateID/Keep/KeepAll
      GetGameMode -> Cast(BaseGameModeInterface) -> GetActorByUniqueID(Container) -> ResolvedActor
      IfThenElse(NotEqual(ResolvedActor, Station)):
        same station (else) -> Array_Add(RuleTemplateID, Rule.TemplateID)
    Completed:
      GetInventoryByType(Station, "PlaceableInventory") -> .ItemList -> ForEachLoop as Item
        IfThenElse(IsValid(Item)) then:
          IfThenElse(Array_Contains(RuleTemplateID, Item.TemplateID)):
            unruled (else) -> ApplyKeepRule(Station, Item.TemplateID, Keep=0, KeepAll=false,
                                             Candidates=ManagedContainers)
"""
import copy
import sys

import os, pathlib
CCMOD = os.environ.get("CCMOD_HOME") or str(pathlib.Path(__file__).resolve().parents[3] / "claude-conan-modder")
sys.path.insert(0, CCMOD)
from ccmod.t3d import parse, connect, connect_exec, auto_layout
from ccmod.t3d.generator import instantiate
from ccmod.t3d.model import Graph

import pathlib
MOD = str(pathlib.Path(__file__).resolve().parents[2])
LIB = CCMOD + r"\library"
WLIB = MOD + r"\.ccmod\library"
SRC_GRAPH = MOD + r"\.ccmod\graphs\stocker_modcontroller_probe_a_live.t3d"

PLACEABLE_BGC = '''"/Script/Engine.BlueprintGeneratedClass'/Game/Systems/Building/Placeables/BP_PlaceableItemContainer.BP_PlaceableItemContainer_C'"'''
KEEPRULE_STRUCT = '''"/Script/CoreUObject.UserDefinedStruct'/Game/Mods/Menu/S_KeepRule.S_KeepRule'"'''
MENU_MC_BGC = '''"/Script/Engine.BlueprintGeneratedClass'/Game/Mods/Menu/Menu_ModController.Menu_ModController_C'"'''
MENU_BPFL_BGC = '''"/Script/Engine.BlueprintGeneratedClass'/Game/Mods/Menu/BPFL_Stocker2.BPFL_Stocker2_C'"'''
MENU_BPFL_DEFAULT = '"/Game/Mods/Menu/BPFL_Stocker2.Default__BPFL_Stocker2_C"'


def pin(n, name, output=None):
    p = n.pin_by_name(name, output=output)
    assert p, f"{n.name} has no pin {name}"
    return p


def setf(n, pn, k, raw, output=None):
    pin(n, pn, output=output)._set(k, raw)


def tmpl_file(path):
    t = parse(open(path, encoding="utf-8-sig").read())
    for n in t.nodes:
        for p in n.pins:
            p.links = []
    return t


def find_by_pin_field(src_graph, pin_name, field, needle):
    for n in src_graph.nodes:
        p = n.pin_by_name(pin_name)
        if p and needle in (p._get(field) or ""):
            nn = copy.deepcopy(n)
            for pp in nn.pins:
                pp.links = []
            return Graph(nodes=[nn])
    raise KeyError((pin_name, field, needle))


def find_by_raw(src_graph, needle, want_class=None):
    for n in src_graph.nodes:
        if want_class and not n.class_path.endswith(want_class):
            continue
        raw = " ".join(t for k, t in n.body if k == "raw")
        if needle in raw:
            nn = copy.deepcopy(n)
            for p in nn.pins:
                p.links = []
            return Graph(nodes=[nn])
    raise KeyError(needle)


IFTHENELSE_RAW = '''Begin Object Class=/Script/BlueprintGraph.K2Node_IfThenElse Name="K2Node_IfThenElse_0"
   NodeGuid=00000000000000000000000000000000
   CustomProperties Pin (PinId=00000000000000000000000000000001,PinName="execute",PinType.PinCategory="exec",PinType.PinSubCategory="",PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
   CustomProperties Pin (PinId=00000000000000000000000000000002,PinName="Condition",PinType.PinCategory="bool",PinType.PinSubCategory="",PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,DefaultValue="true",AutogeneratedDefaultValue="true",PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
   CustomProperties Pin (PinId=00000000000000000000000000000003,PinName="then",PinFriendlyName=NSLOCTEXT("K2Node", "true", "true"),Direction="EGPD_Output",PinType.PinCategory="exec",PinType.PinSubCategory="",PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
   CustomProperties Pin (PinId=00000000000000000000000000000004,PinName="else",PinFriendlyName=NSLOCTEXT("K2Node", "false", "false"),Direction="EGPD_Output",PinType.PinCategory="exec",PinType.PinSubCategory="",PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
End Object'''
IFTHENELSE_T = parse(IFTHENELSE_RAW)

src = parse(open(SRC_GRAPH, encoding="utf-8-sig").read())

KNOT_T = tmpl_file(LIB + r"\flow\knot.t3d")
FEACH_T = tmpl_file(LIB + r"\flow\foreach.t3d")
ADD_T = tmpl_file(LIB + r"\array\array_add.t3d")
CLEAR_T = tmpl_file(LIB + r"\actor\array_clear_int.t3d")
CONTAINS_T = tmpl_file(LIB + r"\actor\array_contains_int.t3d")
NOTEQUAL_T = tmpl_file(LIB + r"\math\not_equal_object.t3d")
GETGAMEMODE_T = tmpl_file(LIB + r"\actor\get_game_mode.t3d")
CAST_T = tmpl_file(LIB + r"\actor\cast_to_basegamemode_interface.t3d")
GETACTOR_T = tmpl_file(LIB + r"\actor\get_actor_by_unique_id.t3d")
ISVALID_T = tmpl_file(LIB + r"\call\is_valid.t3d")
GET_STATIONS_T = tmpl_file(WLIB + r"\stocker\get_managed_stations.t3d")
GET_CONTAINERS_T = tmpl_file(WLIB + r"\stocker\get_managed_containers.t3d")
GET_KEEPRULESV2_T = tmpl_file(WLIB + r"\stocker\get_keeprules_v2.t3d")

BREAKSTRUCT_T = find_by_raw(src, "S_KeepRule.S_KeepRule", want_class="K2Node_BreakStruct")
GET_INV_BY_TYPE_T = find_by_pin_field(src, "inventoryType", "DefaultValue", "PlaceableInventory")
GET_ITEMLIST_T = find_by_raw(src, "ConanSandbox.ItemInventory'\",MemberName=\"ItemList\"", want_class="K2Node_VariableGet")
GET_ITEM_TEMPLATEID_T = find_by_raw(src, "ConanSandbox.GameItem'\",MemberName=\"TemplateID\"", want_class="K2Node_VariableGet")
GET_RULETEMPLATEID_T = find_by_raw(src, 'MemberName="RuleTemplateID"', want_class="K2Node_VariableGet")
APPLYKEEPRULE_T = find_by_raw(src, 'MemberName="ApplyKeepRule"', want_class="K2Node_CallFunction")

SEQ_T = find_by_raw(src, "", want_class="K2Node_ExecutionSequence")
PRINT_T = find_by_raw(src, 'MemberName="PrintString"', want_class="K2Node_CallFunction")
LEN_T = find_by_raw(src, "Array_Length", want_class="K2Node_CallArrayFunction")
CONV_T = find_by_raw(src, "Conv_IntToString", want_class="K2Node_CallFunction")


def make_print(text):
    n = add(PRINT_T)
    setf(n, "InString", "DefaultValue", f'"{text}"')
    return n


def make_count_print(label, array_node, array_pin_name, array_category, array_subobj):
    """execute-less trio: Array_Length(array) -> Conv_IntToString -> PrintString(label + count).
    Returns (entry_exec_pin_owner, that owner's execute pin name) for wiring in."""
    alen = add(LEN_T)
    setf(alen, "TargetArray", "PinType.PinCategory", f'"{array_category}"')
    setf(alen, "TargetArray", "PinType.PinSubCategoryObject", array_subobj)
    setf(alen, "TargetArray", "PinType.ContainerType", "Array")
    connect(array_node, array_pin_name, alen, "TargetArray")
    conv = add(CONV_T)
    connect(alen, "ReturnValue", conv, "InInt")
    pLbl = make_print(label)
    pCount = add(PRINT_T)
    connect(conv, "ReturnValue", pCount, "InString")
    connect_exec(pLbl, pCount)
    return pLbl


def type_array_pin(n, pn, subobj_raw, container, output=None):
    setf(n, pn, "PinType.PinCategory", '"object"', output=output)
    setf(n, pn, "PinType.PinSubCategoryObject", subobj_raw, output=output)
    setf(n, pn, "PinType.ContainerType", container, output=output)


def type_knot(n, category, subcat_obj="None", container="None"):
    for pn in ("InputPin", "OutputPin"):
        setf(n, pn, "PinType.PinCategory", f'"{category}"')
        setf(n, pn, "PinType.PinSubCategoryObject", subcat_obj)
        setf(n, pn, "PinType.ContainerType", container)


g = Graph()


def add(t):
    return instantiate(t, g)[0]


# ---- entry hand-wire (only one: Entry.then -> here) --------------------
knot_entry = add(KNOT_T)
type_knot(knot_entry, "exec")

# ---- outer loop: ManagedStations as Station -----------------------------
stations_get = add(GET_STATIONS_T)
setf(stations_get, "self", "PinType.PinSubCategoryObject", MENU_MC_BGC, output=False)
feach_stations = add(FEACH_T)
type_array_pin(feach_stations, "Array", PLACEABLE_BGC, "Array")
setf(feach_stations, "Array Element", "PinType.PinCategory", '"object"', output=True)
setf(feach_stations, "Array Element", "PinType.PinSubCategoryObject", PLACEABLE_BGC, output=True)

# ---- per-station: clear the RuleTemplateID scratch list -----------------
ruletid_clear_get = add(GET_RULETEMPLATEID_T)
setf(ruletid_clear_get, "self", "PinType.PinSubCategoryObject", MENU_MC_BGC, output=False)
clear_call = add(CLEAR_T)

# ---- inner loop: KeepRulesV2 as Rule -- scope RuleTemplateID to Station -
keeprules_get1 = add(GET_KEEPRULESV2_T)
setf(keeprules_get1, "self", "PinType.PinSubCategoryObject", MENU_MC_BGC, output=False)
feach_rules = add(FEACH_T)
setf(feach_rules, "Array", "PinType.PinCategory", '"struct"')
setf(feach_rules, "Array", "PinType.PinSubCategoryObject", KEEPRULE_STRUCT)
setf(feach_rules, "Array", "PinType.ContainerType", "Array")
setf(feach_rules, "Array Element", "PinType.PinCategory", '"struct"', output=True)
setf(feach_rules, "Array Element", "PinType.PinSubCategoryObject", KEEPRULE_STRUCT, output=True)
setf(feach_rules, "Array Element", "PinType.ContainerType", "None", output=True)

break_rule = add(BREAKSTRUCT_T)
break_rule._replace_prop("StructType", KEEPRULE_STRUCT)
setf(break_rule, "S_KeepRule", "PinType.PinSubCategoryObject", KEEPRULE_STRUCT)

gamemode_get = add(GETGAMEMODE_T)
cast_gm = add(CAST_T)
getactor_a = add(GETACTOR_T)
notequal = add(NOTEQUAL_T)
ite_stationmatch = add(IFTHENELSE_T)
ruletid_add_get = add(GET_RULETEMPLATEID_T)
setf(ruletid_add_get, "self", "PinType.PinSubCategoryObject", MENU_MC_BGC, output=False)
add_call = add(ADD_T)
setf(add_call, "TargetArray", "PinType.PinCategory", '"int"')
setf(add_call, "TargetArray", "PinType.PinSubCategoryObject", "None")
setf(add_call, "TargetArray", "PinType.ContainerType", "Array")
setf(add_call, "NewItem", "PinType.PinCategory", '"int"')
setf(add_call, "NewItem", "PinType.PinSubCategoryObject", "None")

# ---- per-station, after rule loop completes: iterate items --------------
inv_by_type = add(GET_INV_BY_TYPE_T)
itemlist_get = add(GET_ITEMLIST_T)
feach_items = add(FEACH_T)
setf(feach_items, "Array", "PinType.PinCategory", '"object"')
setf(feach_items, "Array", "PinType.PinSubCategoryObject", '''"/Script/CoreUObject.Class'/Script/ConanSandbox.GameItem'"''')
setf(feach_items, "Array", "PinType.ContainerType", "Array")
setf(feach_items, "Array Element", "PinType.PinCategory", '"object"', output=True)
setf(feach_items, "Array Element", "PinType.PinSubCategoryObject", '''"/Script/CoreUObject.Class'/Script/ConanSandbox.GameItem'"''', output=True)

isvalid_item = add(ISVALID_T)
ite_itemvalid = add(IFTHENELSE_T)
item_templateid_get = add(GET_ITEM_TEMPLATEID_T)
ruletid_contains_get = add(GET_RULETEMPLATEID_T)
setf(ruletid_contains_get, "self", "PinType.PinSubCategoryObject", MENU_MC_BGC, output=False)
contains_call = add(CONTAINS_T)
ite_ruled = add(IFTHENELSE_T)
containers_get = add(GET_CONTAINERS_T)
setf(containers_get, "self", "PinType.PinSubCategoryObject", MENU_MC_BGC, output=False)
apply_call = add(APPLYKEEPRULE_T)
setf(apply_call, "self", "PinType.PinSubCategoryObject", MENU_BPFL_BGC)
setf(apply_call, "self", "DefaultObject", MENU_BPFL_DEFAULT)
apply_call._replace_prop(
    "FunctionReference",
    f'(MemberParent={MENU_BPFL_BGC},MemberName="ApplyKeepRule",MemberGuid=A01F81A84B78ED10894F5EA336D8583C)',
)

# =====================  WIRING  ==========================================

# entry -> [sequence] -> outer loop, plus a station-count debug checkpoint
seq_entry = add(SEQ_T)
connect(knot_entry, "OutputPin", seq_entry, "execute")
connect_exec(seq_entry, feach_stations, "then_0", "Exec")
print_stations = make_count_print("MENU_TIDY: stations to process:", stations_get, "ManagedStations", "object", PLACEABLE_BGC)
connect_exec(seq_entry, print_stations, "then_1", "execute")
connect(stations_get, "ManagedStations", feach_stations, "Array")

# cast-failure diagnostic (this pin was dangling in the original too, but silent
# failures here are exactly what past sessions got burned by -- see gotchas memory)
print_castfail = make_print("MENU_TIDY: GetGameMode cast to BaseGameModeInterface FAILED")
connect_exec(cast_gm, print_castfail, "CastFailed", "execute")

# outer LoopBody -> clear -> inner rule loop
connect_exec(feach_stations, clear_call, "LoopBody", "execute")
connect(ruletid_clear_get, "RuleTemplateID", clear_call, "TargetArray")
connect_exec(clear_call, feach_rules, "then", "Exec")
connect(keeprules_get1, "KeepRulesV2", feach_rules, "Array")

# rule loop body: break -> resolve actor -> compare -> maybe add
connect(feach_rules, "Array Element", break_rule, "S_KeepRule")
connect_exec(feach_rules, cast_gm, "LoopBody", "execute")
connect(gamemode_get, "ReturnValue", cast_gm, "Object")
connect_exec(cast_gm, getactor_a, "then", "execute")
connect(cast_gm, "AsBase Game Mode Interface", getactor_a, "self")
connect(break_rule, "Container_4_62E0F0614C1CC5F95CAE6B97F57E9504", getactor_a, "UniqueID")
connect_exec(getactor_a, ite_stationmatch, "then", "execute")
connect(getactor_a, "Actor", notequal, "A")
connect(feach_stations, "Array Element", notequal, "B")
connect(notequal, "ReturnValue", ite_stationmatch, "Condition")
connect_exec(ite_stationmatch, add_call, "else", "execute")
connect(ruletid_add_get, "RuleTemplateID", add_call, "TargetArray")
connect(break_rule, "TemplateID_6_7331DAFA4369B9E2C105A59FAAA510CD", add_call, "NewItem")

# rule loop completes -> [sequence] -> item loop setup, plus a per-station
# rules-matched checkpoint (verifies the per-station RuleTemplateID scoping is
# actually catching rules for this station, not silently empty every time)
seq_rules_done = add(SEQ_T)
connect_exec(feach_rules, seq_rules_done, "Completed", "execute")
connect_exec(seq_rules_done, feach_items, "then_0", "Exec")
ruletid_count_get = add(GET_RULETEMPLATEID_T)
setf(ruletid_count_get, "self", "PinType.PinSubCategoryObject", MENU_MC_BGC, output=False)
print_rulesmatched = make_count_print("MENU_TIDY: rules matched for this station:", ruletid_count_get, "RuleTemplateID", "int", "None")
connect_exec(seq_rules_done, print_rulesmatched, "then_1", "execute")
connect(feach_stations, "Array Element", inv_by_type, "owner")
connect(inv_by_type, "ReturnValue", itemlist_get, "self")
connect(itemlist_get, "ItemList", feach_items, "Array")

# item loop body: validity gate -> ruled gate -> tidy
connect_exec(feach_items, ite_itemvalid, "LoopBody", "execute")
connect(feach_items, "Array Element", isvalid_item, "Object")
connect(isvalid_item, "ReturnValue", ite_itemvalid, "Condition")
connect_exec(ite_itemvalid, ite_ruled, "then", "execute")
connect(feach_items, "Array Element", item_templateid_get, "self")
connect(ruletid_contains_get, "RuleTemplateID", contains_call, "TargetArray")
connect(item_templateid_get, "TemplateID", contains_call, "ItemToFind")
connect(contains_call, "ReturnValue", ite_ruled, "Condition")
connect_exec(ite_ruled, apply_call, "else", "execute")
connect(feach_stations, "Array Element", apply_call, "Station")
connect(item_templateid_get, "TemplateID", apply_call, "TemplateID")
connect(containers_get, "ManagedContainers", apply_call, "Candidates")

auto_layout(g.nodes, origin=(0, 0), dx=260, dy=200, per_column=7)

problems = []
names = {n.name for n in g.nodes}
for n in g.nodes:
    for p in n.pins:
        for (lnn, lp) in p.links:
            if lnn not in names:
                problems.append(f"{n.name}.{p.name} -> missing {lnn}")
                continue
            other = g.by_name(lnn).pin_by_id(lp)
            if other is None:
                problems.append(f"{n.name}.{p.name} -> {lnn} missing pin {lp}")
                continue
            if (n.name, p.pin_id) not in other.links:
                problems.append(f"non-reciprocal: {n.name}.{p.name} -> {lnn}.{other.name}")

out = MOD + r"\.ccmod\graphs\menu_tidymanagedstations_body.t3d"
open(out, "w", encoding="utf-8").write(g.render())
print(f"TidyManagedStations: nodes={len(g.nodes)} wrote={out} problems={len(problems)}")
for pr in problems:
    print("  !", pr)
print(f"  knot -> exec(entry.then) = {knot_entry.name}")
