r"""Fix the SetVisibility InVisibility bug in the item-search row-populate chain.

The compile warning revealed the real answer directly: SetVisibility's actual parameter is
"InVisibility" (byte/ESlateVisibility, PinSubCategory=""), not "Visibility" (what the original
build script guessed, twice). UE auto-generates the real InVisibility pin at its default
("Visible") and keeps the wrongly-named "Visibility" pin around as an orphan warning rather than
erroring outright -- confirmed via a live compile message pasted back this session.

Full pull+edit+repaste of the whole OnTextChanged/filter/rowpopulate chain (104 nodes, saved as
amadanmenu_rowpopulate_broken_setvis_v2), per this project's standard discipline for
EventGraph-level fixes -- preserves every NodeGuid/PinId for anything not being changed, so
re-pasting over the deleted selection restores identical wiring everywhere except the fix itself.

Only the 8 "_f" (Collapsed-branch) nodes need touching -- the 8 "_t" (Visible-branch) nodes
already carry ONLY the correct InVisibility pin at DefaultValue="Visible" with zero compiler
error, because "Visible" happens to equal ESlateVisibility's autogenerated default, so UE never
flagged an orphan there in the first place. Confirmed by inspecting both node shapes directly
from the pulled graph before writing this fix -- not assumed symmetric.

Per row: set InVisibility.DefaultValue="Collapsed", delete the orphaned "Visibility" pin, clear
the node-level error properties (bHasCompilerMessage/ErrorType/ErrorMsg) so the corrected node
doesn't show stale error decoration before the next compile.
"""
import sys

CCMOD = r"<CCMOD_HOME>"
sys.path.insert(0, CCMOD)
from ccmod import db
from ccmod.t3d import parse
from ccmod.workspace import Workspace

MOD = r"<MOD_ROOT>"

ws = Workspace.resolve()
conn = db.connect(ws.cache_db)
row = db.get_graph(conn, "amadanmenu_rowpopulate_broken_setvis_v2")
assert row, "run `ccmod pull --save amadanmenu_rowpopulate_broken_setvis_v2` first"
g = parse(row["t3d"])


def del_prop(n, key):
    needle = key + "="
    n.body = [(kind, text) for (kind, text) in n.body
              if not (kind == "raw" and text.lstrip().startswith(needle))]


fixed = []
for i in range(8):
    name = f"K2Node_CallFunction_SetVis_ItemResult_{i}_f"
    n = g.by_name(name)
    assert n, f"missing {name}"

    invis = n.pin_by_name("InVisibility")
    assert invis, f"{name} missing InVisibility pin"
    invis._set("DefaultValue", '"Collapsed"')

    orphan = n.pin_by_name("Visibility")
    assert orphan, f"{name} missing the orphaned Visibility pin -- did the shape change?"
    n.body = [(kind, item) for (kind, item) in n.body if not (kind == "pin" and item is orphan)]

    del_prop(n, "bHasCompilerMessage")
    del_prop(n, "ErrorType")
    del_prop(n, "ErrorMsg")

    fixed.append(name)

# sanity: confirm the 8 "_t" nodes are untouched and still clean (no orphan, no error props)
for i in range(8):
    n = g.by_name(f"K2Node_CallFunction_SetVis_ItemResult_{i}_t")
    assert n.pin_by_name("Visibility") is None, f"{n.name} unexpectedly has an orphaned Visibility pin"
    assert n.pin_by_name("InVisibility")._get("DefaultValue") == '"Visible"', f"{n.name} InVisibility default changed unexpectedly"

# --- validate (same reciprocal/wildcard checks as every build script) --------------------------
problems = []
names = {n.name for n in g.nodes}
for n in g.nodes:
    for p in n.pins:
        for (lnn, lp) in p.links:
            if lnn not in names:
                problems.append(f"{n.name}.{p.name} -> missing {lnn}")
                continue
            other = g.by_name(lnn).pin_by_id(lp)
            if other is None:
                problems.append(f"{n.name}.{p.name} -> {lnn} missing pin {lp}")
                continue
            if (n.name, p.pin_id) not in other.links:
                problems.append(f"non-reciprocal: {n.name}.{p.name} -> {lnn}.{other.name}")

out = MOD + r"\.ccmod\graphs\amadanmenu_rowpopulate_setvis_fixed.t3d"
open(out, "w", encoding="utf-8").write(g.render())
print(f"fixed nodes: {fixed}")
print(f"total nodes: {len(g.nodes)}   wrote: {out}")
print(f"problems: {len(problems)}")
for pr in problems:
    print("  !", pr)
